project:
  type: website
  output-dir: docs

website:
  title: "Zoe Meziere"
  navbar:
    left:
      - href: zoemeziere.github.io.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
    right:
      - text: "{{< iconify fa6-brands github >}}"
        href: "https://github.com/zoemeziere"
      - text: "{{< iconify fa6-brands twitter >}}"
        href: "https://twitter.com/zoemeziere"

  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Zoe Meziere, 2024"
    
format: 
  html: 
    theme: solar
    toc: true

editor: visual