project:
  type: website
  output-dir: docs

website:
  title: "Zoe Meziere"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
    right:
      - text: "{{< iconify fa6-brands researchgate >}}"
        href: "https://www.researchgate.net/profile/Zoe-Meziere/"
      - icon: twitter
        href: "https://twitter.com/zoe_meziere"
      - icon: github
        href: "https://github.com/ecolology/zoemeziere"

  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Zoe Meziere, 2024"
    
format: 
  html: 
    theme: solar
    toc: false

editor: visual