project:
  type: website
  output-dir: docs

website:
  title: "Zoe Meziere"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
    right:
      - icon: twitter
        href: "https://twitter.com/zoe_meziere"
      - icon: github
        href: "https://github.com/zoemeziere"
      - icon: envelope
        href: "mailto:z.meziere@uq.edu.au"
      - icon: google-scholar
        href: "https://scholar.google.com.au/citations?user=sXHJHJUAAAAJ&hl=en"

  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Zoe Meziere, 2024"
    
format: 
  html: 
    theme: solar
    toc: false
    fontsize: 9pt
    grid: 
      body-width: 1200px
      sidebar-width: 300px
      margin-width: 300px
      gutter-width: 1.5rem

editor: visual