project:
  title: "zoemeziere.github.io"
  type: website
  output-dir: ../docs

website:
  title: "MY WEB SITE"
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Zoe Meziere"

format:
  html:
    theme: cerulean
    toc: true

editor: visual

